### ISSUE TITLE
Ubuntu fractional scaling not working

### ISSUE THREAD

**Issue by stolli83** [digitalbitbox/bitbox-wallet-app#1223]
I have a HDPI display and I'm runing the fractional scaling feature of Ubuntu 20.04 with 150%.
Unfortunatelly is the content of the Bitbox App very small and hard to read.

Please enable the fractional scaling feature that your App is scaling like other applications.
![Bildschirmfoto vom 2021-03-27 21-35-52](https://user-images.githubusercontent.com/57587439/112734192-7f3a3000-8f44-11eb-9256-a10d904562e7.png)

**Comment by x1ddos** [comment]
The app is based on Qt 5.12 at the moment but we're upgrading to Qt 5.15, scheduled for a release in may: we've been holding off due to Ubuntu 16.04 which is end of life on Apr 30. I noticed some very possibly relevant changes between 5.12 and 5.15, in https://doc.qt.io/qt-5/whatsnew514.html:

> Updated High-DPI support:
> 
> - Introduced non-integer scale factors (for example, a scale factor of 150%) that applications can opt-in to use. Use QGuiApplication::highDpiScaleFactorRoundingPolicy or QT_SCALE_FACTOR_ROUNDING_POLICY to set the rounding policy.
> - Added the QT_ENABLE_HIGHDPI_SCALING environment variable, enabling high-DPI scaling based on display DPI. This replaces QT_AUTO_SCREEN_SCALE_FACTOR (now deprecated), and corresponds to the Qt::AA_EnableHighDpiScaling application attribute.

I think it might help with improving HiDPI support.

**Comment by stolli83** [comment]
Meanwhile it‘s working for me but I don‘t know what happend!?

Possible solitions:
- several reboots
- OS updates
- Last Bitbox App update
