### ISSUE TITLE
Improve download CSV file

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#1495]
Got the following report on TG

![Screen Shot 2021-11-27 at 8 41 04 AM](https://user-images.githubusercontent.com/546900/143672882-cddf91a9-6be3-4e67-b04b-f1e90298206a.png)

This probably shouldn't happen, further ideas to improve the UX:
- find out and fix why it shows "Please connect device", this is a bug, it should not route
- add a notification where the file has been downloaded to
- animate the download button into an open file button
- handle if Downloads directory doesn't exist
- ideally: use a native "file save as" dialog

**Comment by BrianCraig** [comment]
The "Please connect device" is because after the CSV is generated, a link element with a local file path href is set, this should not work because it's not part of a specification, and usually blocked by the client (accessing local user files), but somehows it works on linux qt client, opening the file.

I'll address this in the following form:

Add an alert after downloading that says:
"Your summary is ready"
"You can access it on **[path]** from your files explorer"

This will be triggered once the CSV is generated.

I think the idea of making a "file save as" dialog adds a lot of complexity when there are 4 types of clients.

Is this ok for you?

**Comment by thisconnect** [comment]
@BrianCraig thanks for test, so you cannot reproduce the issue on linux in linux qt?

> but somehows it works on linux qt client, opening the file

Yes, iirc there was some custom logic in the Go backend that catches this link and tries to open the file locally in the default application for this filetype.

In this case my suspicion is that something in macOS did change, I guess permission to open a file in Downloads directory.

@jadzeidan can you test this issue on Windows?

**Comment by thisconnect** [comment]
was fixed in https://github.com/digitalbitbox/bitbox-wallet-app/pull/1622
