### ISSUE TITLE
Why is there a max number of accounts?

### ISSUE THREAD

**Issue by resignedScientist** [digitalbitbox/bitbox-wallet-app#1582]
Hello,

I wanted to create a sixth account, but then I get the error:

<img width="681" alt="Screenshot 2022-01-10 at 18 29 25" src="https://user-images.githubusercontent.com/11232656/148811404-a4025d5e-bf1a-4d76-9ecd-c365adab3f5d.png">

Why is there a maximum? Technically there should be more accounts possible.

**Comment by benma** [comment]
The BitBoxApp does not yet implement gap-based account discovery, which is a pre-requisite to be able to add more accounts. Otherwise a user could have a large gap of unused accounts, and scanning would become very difficult in the future.

For now, you could use Electrum (connected to the BitBox02), which supports more accounts. Be sure to write down which accounts you use alongside your backup.

**Comment by x1ddos** [comment]
would be a nice addition to the in-app guide. it doesn't explain this atm:

![image](https://user-images.githubusercontent.com/25405/148922351-32d59c9b-4ef7-4ca9-9f39-ce3bb659a615.png)

**Comment by benma** [comment]
This issue will be fixed for BTC/LTC with https://github.com/digitalbitbox/bitbox-wallet-app/pull/2086 in the next release.

**Comment by NicolaLS** [comment]
@benma closed by [v4.38.1](https://github.com/digitalbitbox/bitbox-wallet-app/releases/tag/v4.38.0)

**Comment by benma** [comment]
@resignedScientist see above, this should now be fixed for BTC/LTC.
