### ISSUE TITLE
Feature Request: Algorand (ALGO) Account Support/Import

### ISSUE THREAD

**Issue by pax85** [digitalbitbox/bitbox-wallet-app#1711]
Hi,

I'd like to give a shoutout to the Algorand Ecosystem (ALGO Coin and ASA Tokens) for easy, fast and cheap transactions and DeFi usage. 
I would therefore like to propose support for the Algorand Ecosystem. Here is some further information:

- CoinGecko: https://www.coingecko.com/en/coins/algorand
- Algorand Developer Portal: https://developer.algorand.org/

kind regards

**Comment by jadzeidan** [comment]
Hi @pax85, thanks for the feature request. Currently, we don't plan on adding Algorand because we don't get many requests for it. Adding altcoins requires a lot of dev work to implement and maintain, so we try to limit it to coins where we see a lot of demand and think they are likely to stay around into the future. But if we see the demand for Algorand increase then we can reconsider it.
