### ISSUE TITLE
Feature Request: Support USDT on Tron (TRC-20)

### ISSUE THREAD

**Issue by micressor** [digitalbitbox/bitbox-wallet-app#2113]
I would like to be able to use Tether USDT on the Tron network directly through Bitbox02.

Is there any chance in the medium term that this will be supported?
I have absolutely no interest in another/2. hardware wallet. ;-)

**Comment by jadzeidan** [comment]
Hi @micressor, thanks for the feature request. Currently we don't have plans to add other blockchains, because it is a lot of effort to implement and maintain. And there are many different chains that different users want. However if we consistently get many requests for a specific chain, we can consider it.

**Comment by micressor** [comment]
Too bad. Maybe you can recommend another wallet app that makes this possible together with bitbox as a keystore?

**Comment by benma** [comment]
Sorry to disappoint, but the BitBox02 itself does not support Tron, so no other wallet app will work with it for Tron.

**Comment by micressor** [comment]
Ledger is to my knowledge currently the only hardware wallet that supports the tron network. Possibly a chance for bitbox.

Hope dies last - I believe in you ;-)
