### ISSUE TITLE
drop node 9.x for travis linux

### ISSUE THREAD

**Issue by thisconnect** [digitalbitbox/bitbox-wallet-app#352]
nodejs is installed twice for travis/linux 
search for `node --version`
on a recent build https://travis-ci.org/digitalbitbox/bitbox-wallet-app/jobs/505799528

```bash
# line 444
$ node --version
v10.13.0

# line 1932
node --version
v9.11.2
```
travis config
https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/.travis.yml#L14

nodejs 9.x in `scripts/docker_install.sh`
https://github.com/digitalbitbox/bitbox-wallet-app/blob/master/scripts/docker_install.sh#L21

is it possible that nodejs is defined in the docker image?

where is the dockerimage `shiftcrypto/qt5` coming from?
(what is the source of https://hub.docker.com/r/shiftcrypto/qt5 used here https://github.com/digitalbitbox/bitbox-wallet-app/blob/13a36957690f4eabd2894f7529083054af6f1018/Dockerfile#L15)

**Comment by benma** [comment]
the first one is from the Travis environment, based on travis.yml. This is really needed for macOS, where we don't build from docker.

The second entry is from inside the docker process, and the one that is used in the actual build process.

Not sure how to have `language: nodejs` only apply to the macOS build on travis, but in any case, it doesn't hurt the linux build.

Related: https://github.com/digitalbitbox/bitbox-wallet-app/pull/353

**Comment by thisconnect** [comment]
the linux build takes twice as long on travis than the travis mac
is there a dockerfile for the image https://hub.docker.com/r/shiftcrypto/qt5

**Comment by benma** [comment]
Yeah, it's here:

https://github.com/digitalbitbox/bitbox-wallet-app/blob/a211f052e54d5d776a294515bcdde4c2c7d96f59/frontends/qt/docker-qt5base/Dockerfile

It might take longer because the Dockerfile (the [main one](https://github.com/digitalbitbox/bitbox-wallet-app/blob/a211f052e54d5d776a294515bcdde4c2c7d96f59/Dockerfile), not the one above) is built every time.

Might help to have that on dockerhub as well, so travis only has to pull it instead of build it.

**Comment by thisconnect** [comment]
thanks https://github.com/digitalbitbox/bitbox-wallet-app/commit/62722cd1304f67cb71fc09153fb7ce5654d71905
