### ISSUE TITLE
App crashes during initial setup

### ISSUE THREAD

**Issue by daniel-vera-g** [digitalbitbox/bitbox-wallet-app#436]
During the initial setup, after closing the app and reopening it with the BitBox 02 plugged in, the Application crashes.

## Expected Behavior

The app should open and continue where it was closed. 

## Current Behavior

The app immediately crashes and probably expects an already created wallet. 

## Possible Solution

Fix/Check the startup code for the application?

## Steps to Reproduce

1. Open the application
1. Plugin the new BitBox 02
1. Go on till the `Insert SD-Card step`:

![IMG_20190618_202723](https://user-images.githubusercontent.com/28257108/59827396-1c0b7a80-9328-11e9-8260-177d7700f5f6.jpg)

4. Close the application with the BitBox 02 Plugged in
5. Restart the application

## Current solution

1. Unplug BitBox 02
1. Restart application
1. Plug BitBox 02 in

## Context (Environment)

1. Ubuntu 18.04
1. APP VERSION: 4.9.0 installed through the .deb package.
1. BitBox 02 Beta
1. Using USB-C/Thunderbolt in an Dell XPS 13

**Comment by benma** [comment]
Thanks a lot for your bug report, @daniel-vera-g 

I assume this happened while the BitBox02 was showing the 'insert sd card' screen. The issue is that when the app closes, the BitBox02 stays in this screen, blocking new usb connections (e.g. when the app is restarted). The same happens e.g. during password entry. We will work on a fix in the firmware app (as well as more graceful handling in the app).

**Comment by benma** [comment]
This issue could only be addressed after restructuring our communication architecture to be asynchronous. This has happened in the meantime, so work on this issue was unblocked. 

https://github.com/digitalbitbox/bitbox02-firmware/pull/592 solves this particular issue.

There are more instances still of synchronous blocking communication, so restarting the app during one of those is still problematic, but it's only a matter of time until all of them are fixed.
