### ISSUE TITLE
bitbox-wallet-app not working with eps 1.7

### ISSUE THREAD

**Issue by Garleb** [digitalbitbox/bitbox-wallet-app#508]
i'd like to add my eps server to my bitbox app.
After downloading the certificate when pressing check i get the following error:

Failed to unmarshal response: ["ElectrumPersonalServer 0.1.7", 1.2]: Failed to unmarshal JSON: json: cannot unmarshal number into Go value of type string

When i press back then try to add my eps again with "check" button its just working indefinitely.

EPS log says client is connected.

**Comment by benma** [comment]
Hi

This issue was fixed a while ago at EPS, see this issue: https://github.com/chris-belcher/electrum-personal-server/issues/135

Unfortunately, there it looks like there hasn't been a new release of EPS which contains the fix. In the meantime, you can try running EPS from source: https://github.com/chris-belcher/electrum-personal-server

**Comment by Garleb** [comment]
Hi,
thank you very much for ur quick reply, its working now!
