### ISSUE TITLE
"Connect your own full node" without Electrum server

### ISSUE THREAD

**Issue by x1ddos** [digitalbitbox/bitbox-wallet-app#615]
In other words, why should I bother with an Electrum server if I'm already running a bitcoind from https://github.com/bitcoin/bitcoin or something else listed on https://en.bitcoin.it/wiki/Full_node#How_to_run_a_full_node ? For instance, I see bitcoind provides [sendrawtransaction](https://bitcoincore.org/en/doc/0.18.0/rpc/rawtransactions/sendrawtransaction/) RPC. Would it be possible for the BitBox app to use that directly to broadcast a transaction?

It seems the BitBox app supports only Electrum. What was the reasoning? Why not others?

Also, "Connect your own full node" feels a bit confusing. It should either read "Connect your own Electrum server" or support other full nodes like bitcoind otherwise.

**Comment by benma** [comment]
A wallet like the BitBoxApp needs an index of all transactions per address in your wallet, not just `sendrawtransaction`.

An electrum server is not a standalone thing, it usually runs in combination **with** Bitcoin Core, and provides the address<->transactions index, which Bitcoin Core does not provide out of the box.

ElectrumX, [Electrs](https://github.com/romanz/electrs) etc. provide a full index of all txs, while [electrum personal server](https://github.com/chris-belcher/electrum-personal-server) does it only for the addresses in your wallet. We default to using a full index, as the latter harder to configure and use and recovery is terrible (needs a rescan of the full chain).

We could provide direct bindings to track your own addresses through Bitcoin Core. We are not doing this because Electrum Personal server does just that, but provides it to the App in the Electrum protocol, which by now is a defacto-standard for querying the chain. It is simpler to support only one protocol than multiple.

We might support Bitcoin Core directly in the future as well, but it is not a priority due to the above reasons (Electrum personal server works, and recovery is bad UX).

Find more info in the [21lectures slides on the topic](https://github.com/21Lectures/Advanced-Course/blob/db05f18feedd57ce0fb155917a587b0c841c1e29/day3/All%20about%20Wallets.pdf), starting with page 22 (Blockchain Indexing Techniques)

Note that ElectrumX in the new version is [currently not working](https://github.com/digitalbitbox/bitbox-wallet-app/issues/499) with the BitBoxApp. Fixing this is medium prio. I recommend to go with Electrs or Electrum Personal Server.

**Comment by x1ddos** [comment]
Thanks for super useful explanation! I always knew I should've followed your 21lectures. :)

> Electrum protocol, which by now is a de-facto standard for querying the chain

Would it make sense for someone to propose a BIP?

Anyway, what still confuses me is, while BitBox app says "connect your own full node", one can hardly find a mention of Electrum when searching "run own full node": https://duckduckgo.com/?q=run+own+bitcoin+full+node or https://duckduckgo.com/?q=run+own+full+node.

**Comment by thisconnect** [comment]
The guide on "Connect to your full node" currently only has 1 item:

– What is this?
It is possible to power your wallet with your own full nodes instead of using Shift servers.


How about adding the explanation here to the guide?
(jeopardy)

– Can I connect directly to Bitcoin Core?
https://github.com/digitalbitbox/bitbox-wallet-app/issues/615#issuecomment-546803423

---

Additionally consider linking the excellent blogpost by @TheCharlatan 
https://medium.com/shiftcrypto/regain-your-privacy-by-connecting-a-bitcoin-full-node-to-your-bitbox-wallet-58c96eb1f345

btw. the blogpost links to https://github.com/chris-belcher/electrum-personal-server 
would be great to update it to https://github.com/romanz/electrs :)

**Comment by thisconnect** [comment]
should I open a new issue?

**Comment by x1ddos** [comment]
Thanks for useful links, @thisconnect! I wish some of it were in the guide.

> should I open a new issue?

+1 and renaming to "Connect to your own Electrum node" would be nice imho, too. It doesn't have to be a "full node", does it. BitBox app wouldn't care anyway. The "full node" part is confusing.

**Comment by benma** [comment]
+1 for new issue to add something to the guide.

Fyi, the title of the tab in the page where you add a server says `Bitcoin Electrum Servers` (of course can be made more clear).

Renaming `Connect to your own Electrum node`

This won't be necessary, as we plan to move the whole section to a sidebar entry "Node management" (or some other fitting name).

**Comment by thisconnect** [comment]
@x1ddos and @benma I opened https://github.com/digitalbitbox/bitbox-wallet-app/issues/617
please add guide entries (questions/answers) that should be implemented.
